### ISSUE TITLE
Tugas 1 - Membuat Halaman Read Dosen

### ISSUE THREAD

**Issue by Sriiindarti** [Sriiindarti/latihan-web-2022#1]
Buatkan halaman dosen. Yang dapat memperlihatkan nama dosen yang tertera.
Dimana dalamnya terdapat beberapa komponen berikut ini :
1. No Induk Dosen
2. Nama Dosen
3. Email
4. No Telepon
5. Mata Kuliah
6. Tahun Masuk

buatkan dalam tampilan sederhana saja, yang terpenting sudah bisa terhubung ke database MYSQL
Terimakasih😎

**Comment by DaffanTS** [comment]
Tugas sudah selesai Sri

**Comment by Sriiindarti** [comment]
Tugasnya diterima Daffan. Keren
